name: CI + Release

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['main']

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Compile TypeScript
        run: npm run build

      - name: Run unit tests
        run: npm run test:unit

      - name: Upload test results (even if tests fail)
        if: always()  # Ensure this step runs even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/

  release:
    name: Build & Release (main only)
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build production artifact
        run: npm run build

      - name: Upload build artifact
        if: always()  # Ensure the artifact is uploaded even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: web-release
          path: dist/

      - name: Deploy to GitHub Pages
        if: success()  # Only deploy if the build is successful
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist